#!/bin/bash -e
# generic preseeding of inithooks.conf

MASTERPASS=$(mcookie | cut --bytes 1-8)

cat>$INITHOOKS_CONF<<EOF
export LDAP_BASEDN=DEFAULT
export LDAP_BINDDN="cn=nss_pam,dc=example,dc=com"
export LDAP_PASS=$MASTERPASS
export LDAP_SERVER=127.0.0.1
EOF

